$out = "views/Dashboard/Adminventas.php"
$lines = @()
$lines += '<?php'
$lines += 'if (session_status() === PHP_SESSION_NONE) { session_start(); }'
$lines += 'if (!isset($_SESSION["logged_in"]) || $_SESSION["logged_in"] !== true) { header("Location: ../Usuario/login.php"); exit; }'
$lines += '$_rol_actual = strtolower($_SESSION["usuario"]["rol"] ?? $_SESSION["rol"] ?? "");'
$lines += 'if ($_rol_actual === "empleado") { header("Location: Empleado.php"); exit; }'
$lines += '$titulo = "Punto de Venta";'
$lines += '$productos = []; $categorias = []; $metodos_pago = [];'
$lines += '$resumen_hoy = ["total_ventas" => 0, "total_ingresos" => 0];'
$lines += '$_error_bd = "";'
$lines += 'try {'
$lines += '    require_once __DIR__ . "/../../config/database.php";'
$lines += '    require_once __DIR__ . "/../../models/Producto.php";'
$lines += '    require_once __DIR__ . "/../../models/Categoria.php";'
$lines += '    require_once __DIR__ . "/../../models/Venta.php";'
$lines += '    $db = (new Database())->conectar();'
$lines += '    $productos = (new Producto($db))->listarActivos();'
$lines += '    $categorias = (new Categoria($db))->listarActivas();'
$lines += '    $resumen_hoy = (new Venta($db))->resumenDiario();'
$lines += '    $stmtMP = $db->query("SELECT id_metodo, nombre FROM metodos_pago WHERE activo = 1 ORDER BY nombre");'
$lines += '    $metodos_pago = $stmtMP ? $stmtMP->fetchAll(PDO::FETCH_ASSOC) : [];'
$lines += '} catch (Throwable $e) {'
$lines += '    $_error_bd = "No se pudieron cargar los datos.";'
$lines += '    error_log("[SIGI] Adminventas.php Error: " . $e->getMessage());'
$lines += '}'
$lines += 'require_once __DIR__ . "/../layouts/header.php";'
$lines += 'require_once __DIR__ . "/../layouts/sidebar.php";'
$lines += '?>'
$lines | Set-Content -Path $out -Encoding UTF8
Write-Host "PHP header written"
